---
title: "BDNF on fraction new RNA"
author: "Maddie Lombardo"
date: "1/24/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(PCAtools)
library(ggpubr)
```

```{r new RNA filepath}
new_RNA_file_path <- file.path(here::here("data","grandslam_new_rna.csv"))
```

```{r}
new_RNA <- read_csv(new_RNA_file_path)
```

```{r}
the_stuff <- list("DYNC1H1","DYNC1I2","DYNC1LI1","DYNLL1","DCTN1","DCTN2","DCTN3","HOOK3","BICD2", "KIF1A", "KIF1B", "KIF5A","KIF5B","KIF5C","KIF13A","KIF13B")
new_RNA %>% 
  filter(symbol %in% the_stuff) %>% 
  ggplot(mapping = aes(x = time , y = fraction_new_rna, color = condition))+
  geom_jitter()+
  geom_smooth(se = FALSE)+
  theme_pubr(legend = c("right"))+
  labs_pubr(base_size = 8)+
    facet_wrap(~symbol, scales = "free")
```

now i'm looking how BDNF affects the total RNA levels of these same genes..
```{r}
full_de <- read_csv(here::here("data","full_total_rna.csv"))

full_de %>% 
  filter(gene_name %in% the_stuff) %>% 
  mutate(significantly_de = padj < 0.1) %>% 
  ggplot(aes(x = as.character(time), y = log2FoldChange,group = gene_name))  + 
  geom_hline(yintercept = 0, size = 1.3)  + 
  geom_line(size = 1.3,show.legend = F) + 
  geom_point(pch = 21, size = 4,aes(fill = significantly_de))  + 
  facet_wrap(~gene_name) + 
  ggpubr::theme_pubr() + 
  labs(fill = "Change is Significant?",x = 'Labelling + BDNF time',ylab = 'Log2FoldChange Total RNA') 
```

```{r graph no time 6}
new_RNA %>% 
  filter(symbol %in% the_stuff) %>% 
  filter(time != 6) %>% 
  ggplot(mapping = aes(x = time , y = fraction_new_rna, color = condition))+
  geom_jitter(width = 0.1)+
  geom_smooth(se = FALSE)+
  theme_pubr(legend = c("right"))+
  labs_pubr(base_size = 8)+
    facet_wrap(~symbol, scales = "free")
```

```{r dynein/dynactin list}
dynein_dynactin_file_path <- file.path(here::here("data","confirmed and candidate genes for dynein dynactin.csv"))

dynein_dynactin_list <- read_csv(dynein_dynactin_file_path)
dynein_stuff <- dynein_dynactin_list$gene

new_RNA %>% 
  filter(symbol %in% dynein_stuff) %>% 
  filter(estimate_new_credible_interval < 0.2) %>% 
  ggplot(mapping = aes(x = time , y = fraction_new_rna, color = condition))+
  geom_jitter()+
  geom_smooth(se = FALSE)+
  theme_pubr(legend = c("right"))+
  labs_pubr(base_size = 8)+
    facet_wrap(~symbol, scales = "free")

#no 6 hour
new_RNA %>% 
  filter(symbol %in% dynein_stuff) %>% 
  filter(estimate_new_credible_interval < 0.2) %>% 
  filter(time != 6) %>% 
  ggplot(mapping = aes(x = time , y = fraction_new_rna, color = condition))+
  geom_jitter()+
  geom_smooth(se = FALSE)+
  theme_pubr(legend = c("right"))+
  labs_pubr(base_size = 8)+
    facet_wrap(~symbol, scales = "free")

full_de %>% 
  filter(gene_name %in% dynein_stuff) %>% 
  mutate(significantly_de = padj < 0.1) %>% 
  ggplot(aes(x = as.character(time), y = log2FoldChange,group = gene_name))  + 
  geom_hline(yintercept = 0, size = 1.3)  + 
  geom_line(size = 1.3,show.legend = F) + 
  geom_point(pch = 21, size = 4,aes(fill = significantly_de))  + 
  facet_wrap(~gene_name) + 
  ggpubr::theme_pubr() + 
  labs(fill = "Change is Significant?",x = 'Labelling + BDNF time',ylab = 'Log2FoldChange Total RNA') 
```



