---
title: "Differential expression no well 4"
author: "Maddie Lombardo"
date: "1/14/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(annotables)
library(PCAtools)
library(gprofiler2)
library(pcaExplorer)
library(AnnotationDbi)
library(org.Hs.eg.db)
library(clusterProfiler)
```

reading the functions in that i'll use
```{r reading the functions in}
source(here::here('run_standard_deseq.R'))
source(here::here('make_volcano_plot.R'))
```

reading in the files
```{r read in files}
feature_counts_file_path <- file.path(here::here("data","feature_counts_bdnf_No4"))
```

running a deseq 1hr
```{r deseq2 1h}
one_hour_dds <- run_standard_deseq(feature_counts_file_path, base_grep = "CONTROL",
                              contrast_grep = "BDNF", 
                              grep_pattern = "1hr",
                              baseName = "control",
                              contrastName = 'BDNF')
```

make a volcano plot 1hr
```{r volcano plot 1h}
one_hour_volcano <- make_volcano_plot(one_hour_dds$results_table)
```

deseq 2hr
```{r deseq 2h}
two_hour_dds <- run_standard_deseq(feature_counts_file_path, base_grep = "CONTROL",
                              contrast_grep = "BDNF", 
                              grep_pattern = "2hr",
                              baseName = "control",
                              contrastName = 'BDNF')
```

volcano 2hr
```{r volcano 2h}
two_hr_volcano <- make_volcano_plot(two_hour_dds$results_table)
```

deseq 6h
```{r deseq 6h}
six_hr_dds <- run_standard_deseq(feature_counts_file_path, base_grep = "CONTROL",
                              contrast_grep = "BDNF", 
                              grep_pattern = "6hr",
                              baseName = "control",
                              contrastName = 'BDNF')
```

volcano 6h
```{r volcano 6h}
six_hr_volcano <- make_volcano_plot(six_hr_dds$results_table)
```

now we are going to use the deseq data to do gene ontology
hour 1
```{r GO 1hr}
results_1hr <- one_hour_dds$results_table

up_1hr_ensembl <- results_1hr %>% 
  dplyr::filter(padj < 0.05 & log2FoldChange > 0 ) %>% 
  mutate(ensembl = gsub("\\..*", "", Geneid)) %>% 
  arrange(-log2FoldChange) %>% 
  pull(ensembl)

down_1hr_ensembl <- results_1hr %>% 
  dplyr::filter(padj < 0.05 & log2FoldChange < 0 ) %>% 
  mutate(ensembl = gsub("\\..*", "", Geneid)) %>% 
  arrange(log2FoldChange) %>% 
  pull(ensembl)

gp_up_1hr = gost(up_1hr_ensembl, organism = "hsapiens", ordered_query = TRUE) 
gostplot(gp_up_1hr)
gp_down_1hr = gost(down_1hr_ensembl, organism = "hsapiens", ordered_query = TRUE)
gostplot(gp_down_1hr)

```

GO hr 2
```{r go 2h}
results_2hr <- two_hour_dds$results_table

up_2hr_ensembl <- results_2hr %>% 
  filter(padj < 0.05 & log2FoldChange > 0 ) %>% 
  mutate(ensembl = gsub("\\..*", "", Geneid)) %>% 
  pull(ensembl)

down_2hr_ensembl <- results_2hr %>% 
  filter(padj < 0.05 & log2FoldChange < 0 ) %>% 
  mutate(ensembl = gsub("\\..*", "", Geneid)) %>% 
  pull(ensembl)



gp_up_2hr <-  gost(up_2hr_ensembl, organism = "hsapiens")

gp_down_2hr <-  gost(down_2hr_ensembl, organism = "hsapiens")
```

go 6h
```{r go 6h}
results_6hr <- six_hr_dds$results_table

up_6hr_ensembl <- results_6hr %>% 
  filter(padj < 0.05 & log2FoldChange > 0 ) %>% 
  mutate(ensembl = gsub("\\..*", "", Geneid)) %>% 
  pull(ensembl)

down_6hr_ensembl <- results_6hr %>% 
  filter(padj < 0.05 & log2FoldChange < 0 ) %>% 
  mutate(ensembl = gsub("\\..*", "", Geneid)) %>% 
  pull(ensembl)

gp_up_6hr = gost(up_6hr_ensembl, organism = "hsapiens")
gp_down_6hr = gost(down_6hr_ensembl, organism = "hsapiens")
```


```{r clusterprofiler GO 1hr}

bg_ids_1hr <- one_hour_dds$results_table$Geneid %>% gsub("\\..*", "", .) 

e_go_cc_1hr_up <- enrichGO(gene          = up_1hr_ensembl,
                universe      = bg_ids_1hr,
                keyType = "ENSEMBL",
                OrgDb         = org.Hs.eg.db,
                ont           = "CC",
                pAdjustMethod = "BH",
                pvalueCutoff  = 0.01,
                qvalueCutoff  = 0.05,
        readable      = TRUE)

e_go_mf_1hr_up <- enrichGO(gene          = up_1hr_ensembl,
                universe      = bg_ids_1hr,
                keyType = "ENSEMBL",
                OrgDb         = org.Hs.eg.db,
                ont           = "MF",
                pAdjustMethod = "BH",
                pvalueCutoff  = 0.01,
                qvalueCutoff  = 0.05,
        readable      = TRUE)

e_go_bp_1hr_up <- enrichGO(gene          = up_1hr_ensembl,
                universe      = bg_ids_1hr,
                keyType = "ENSEMBL",
                OrgDb         = org.Hs.eg.db,
                ont           = "BP",
                pAdjustMethod = "BH",
                pvalueCutoff  = 0.01,
                qvalueCutoff  = 0.05,
        readable      = TRUE)

if(any(e_go_cc_1hr_up@result$p.adjust <0.01)){
  cnetplot(e_go_cc_1hr_up)
  dotplot(e_go_cc_1hr_up)
  }

if(any(e_go_bp_1hr_up@result$p.adjust <0.01)){
  cnetplot(e_go_bp_1hr_up)
  dotplot(e_go_bp_1hr_up)}

```

```{r clusterProfiler GO at 2hr}
bg_ids_2hr <- two_hour_dds$results_table$Geneid %>% gsub("\\..*", "", .) 

e_go_cc_2hr_up <- enrichGO(gene          = up_2hr_ensembl,
                universe      = bg_ids_2hr,
                keyType = "ENSEMBL",
                OrgDb         = org.Hs.eg.db,
                ont           = "CC",
                pAdjustMethod = "BH",
                pvalueCutoff  = 0.01,
                qvalueCutoff  = 0.05,
        readable      = TRUE)

e_go_mf_2hr_up <- enrichGO(gene          = up_2hr_ensembl,
                universe      = bg_ids_2hr,
                keyType = "ENSEMBL",
                OrgDb         = org.Hs.eg.db,
                ont           = "MF",
                pAdjustMethod = "BH",
                pvalueCutoff  = 0.01,
                qvalueCutoff  = 0.05,
        readable      = TRUE)

e_go_bp_2hr_up <- enrichGO(gene          = up_2hr_ensembl,
                universe      = bg_ids_2hr,
                keyType = "ENSEMBL",
                OrgDb         = org.Hs.eg.db,
                ont           = "BP",
                pAdjustMethod = "BH",
                pvalueCutoff  = 0.01,
                qvalueCutoff  = 0.05,
        readable      = TRUE)

if(any(e_go_cc_2hr_up@result$p.adjust <0.01)){
  cnetplot(e_go_cc_2hr_up)
  dotplot(e_go_cc_2hr_up)
  }

if(any(e_go_bp_2hr_up@result$p.adjust <0.01)){
  cnetplot(e_go_bp_2hr_up)
  dotplot(e_go_bp_2hr_up)}
```

```{r clusterProfiler GO at 6hr}
bg_ids_6hr <- six_hr_dds$results_table$Geneid %>% gsub("\\..*", "", .) 

e_go_cc_6hr_up <- enrichGO(gene          = up_6hr_ensembl,
                universe      = bg_ids_6hr,
                keyType = "ENSEMBL",
                OrgDb         = org.Hs.eg.db,
                ont           = "CC",
                pAdjustMethod = "BH",
                pvalueCutoff  = 0.01,
                qvalueCutoff  = 0.05,
        readable      = TRUE)

e_go_mf_6hr_up <- enrichGO(gene          = up_6hr_ensembl,
                universe      = bg_ids_6hr,
                keyType = "ENSEMBL",
                OrgDb         = org.Hs.eg.db,
                ont           = "MF",
                pAdjustMethod = "BH",
                pvalueCutoff  = 0.01,
                qvalueCutoff  = 0.05,
        readable      = TRUE)

e_go_bp_6hr_up <- enrichGO(gene          = up_6hr_ensembl,
                universe      = bg_ids_6hr,
                keyType = "ENSEMBL",
                OrgDb         = org.Hs.eg.db,
                ont           = "BP",
                pAdjustMethod = "BH",
                pvalueCutoff  = 0.01,
                qvalueCutoff  = 0.05,
        readable      = TRUE)

if(any(e_go_cc_6hr_up@result$p.adjust <0.01)){
  cnetplot(e_go_cc_6hr_up)
  dotplot(e_go_cc_6hr_up)
  }

if(any(e_go_bp_6hr_up@result$p.adjust <0.01)){
  cnetplot(e_go_bp_6hr_up)
  dotplot(e_go_bp_6hr_up)}
```

