---
title: "Differential_expression_full_BDNF"
author: "Maddie Lombardo"
date: "1/11/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(annotables)
library(tidyverse)
```

read in functions
```{r}
source(here::here('make_volcano_plot.R'))
source(here::here('run_standard_deseq.R'))
source(here::here('make_deseq_dfs.R'))
source(here::here('create_feature_count_table.R'))
```

read in the files
```{r}
featureCounts_file_path <- file.path(here::here(),"data","feature_counts_bdnf_full_experiment")

res <- run_standard_deseq(featureCounts_file_path,
                   base_grep = "CONTROL",
                   contrast_grep = "BDNF",
                   grep_pattern = "1hr",
                   baseName = "control",
                   contrastName = 'bdnf')


meta_file_path <- file.path(here::here(),"data", "full_experiment_metadata.csv")

metadata <- fread(meta_file_path)

```


first, do a PCA plot of all samples
```{r}
featureCounts_file_path <- file.path(here::here(),"data","feature_counts_bdnf_full_experiment")
counts_object <- create_feature_count_table(featureCounts_file_path)

#remove the gene name column, turn it into a rowname
counts_object <- counts_object %>% 
    select(-gene_name) %>% 
    column_to_rownames('Geneid') 

meta_df <- metadata %>% 
  mutate(well = as.factor(well)) %>% #turn it into a factor so when you color by it with the biplot function it doesn't give you a gradient
    column_to_rownames('sample_name')

#reorder the columns of counts object to match the order of the rows in meta_df
counts_object <- counts_object[match(rownames(meta_df),colnames(counts_object))]

library(PCAtools)
p <- PCAtools::pca(counts_object , metadata = meta_df, removeVar = 0.1)

screeplot <- screeplot(p, axisLabSize = 18, titleLabSize = 22)

biplot(p,
       x = "PC1",
       y = "PC2",
       colby = 'cond')
```

now I'm going to get and arrange the different pca gene loadings

```{r}

pc1_gene_loadings = p$loadings %>% 
    dplyr::select(PC1) %>% 
    rownames_to_column('ensgene') %>% 
    mutate(ensgene = gsub("\\..*", "", ensgene)) %>% 
    left_join(annotables::grch38 %>%   dplyr::select(ensgene,symbol))  %>% 
    arrange(-PC1)

pc2_gene_loadings = p$loadings %>% 
  dplyr::select(PC2) %>% 
  rownames_to_column('ensgene') %>% 
   mutate(ensgene = gsub("\\..*", "", ensgene)) %>%
  left_join(annotables::grch38 %>% 
dplyr::select(ensgene,symbol)) %>% 
  arrange(-PC2)
```

looking at expression of top 15 genes
```{r}
#first removing the ".x" bit from counts_object
counts_object <- counts_object %>% 
  rownames_to_column('ensgene') %>% 
  mutate(ensgene = gsub("\\..*", "", ensgene))
  
pc1_counts <- counts_object %>% 
    left_join(pc1_gene_loadings, by = 'ensgene') %>%
    filter(!is.na(PC1)) %>% 
    select(-ensgene) %>% 
    melt(id.vars = c("symbol","PC1")) %>% 
    slice_max(PC1, n = 15) %>% 
    mutate(symbol = fct_reorder(symbol,-PC1)) %>% 
    separate(variable, into = c("condition","plate","labelling_time")) %>% 
    ggplot(aes(x = labelling_time, y = value, fill = condition)) + 
    geom_col(position = "dodge2") + 
    facet_wrap(~symbol)
```

pulling out top 100 to determine cutoff

```{r}
top_100_PC1 <- pc1_gene_loadings %>% 
    slice_max(PC1, n = 100)

top_100_PC1 %>% 
     mutate(symbol = fct_reorder(symbol, PC1)) %>% 
     ggplot(aes(x = symbol, y = PC1)) + 
     geom_col(position = "dodge2") +
     coord_flip()

top_100_PC2 <- pc2_gene_loadings %>% 
    slice_max(PC2, n = 100)

top_100_PC2 %>% 
     mutate(symbol = fct_reorder(symbol, PC2)) %>% 
     ggplot(aes(x = symbol, y = PC2)) + 
     geom_col(position = "dodge2") +
     coord_flip()
```

make volcano plot

```{r}
make_volcano_plot(res)
```

