---
title: "YTH exploration"
author: "Maddie Lombardo"
date: "3/2/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(data.table)
library(corrplot)
```

axonal fisher coorelation plot code from AL
```{r correlation plots from AL}
yth <- as.data.table(janitor::clean_names(fread("C:/Users/mlomb/Desktop/tracked_files_github/bdnf_4su/data/YTH bound mRNAs.csv")))
new_ratio_bayesian_p_de <- read_csv("C:/Users/mlomb/Desktop/tracked_files_github/bdnf_4su/data/new_ratio_bayesian_p_de.csv")
ax <- readLines("C:/Users/mlomb/Desktop/tracked_files_github/bdnf_4su/data/axonal_genes.txt")



one_hour = new_ratio_bayesian_p_de %>% 
    filter(new_rna_sig != "unclear") %>% 
    mutate(gene = gsub("\\..*", "", gene)) %>%  
    left_join(annotables::grch38 %>% select(ensgene,symbol), by = c("gene" = "ensgene")) %>% 
    select(time,symbol,total_rna_sig,new_rna_sig) %>% 
    filter(!is.na(symbol)) %>% 
    unique() %>% 
    mutate(axonal = symbol %in% ax) %>% 
    filter(time == 1) %>% 
    mutate(total_new = paste(total_rna_sig,new_rna_sig,sep = "_")) %>% 
    select(total_new,axonal)  %>% 
    table() %>% 
    chisq.test()

two_hour = new_ratio_bayesian_p_de %>% 
    mutate(gene = gsub("\\..*", "", gene)) %>%
    filter(new_rna_sig != "unclear") %>% 
    left_join(annotables::grch38 %>% select(ensgene,symbol), by = c("gene" = "ensgene")) %>% 
    select(time,symbol,total_rna_sig,new_rna_sig) %>% 
    filter(!is.na(symbol)) %>% 
    unique() %>% 
    mutate(axonal = symbol %in% ax) %>% 
    filter(time == 2) %>% 
    mutate(total_new = paste0(total_rna_sig,"_",new_rna_sig)) %>% 
    select(total_new,axonal) %>% 
    table() %>% 
    chisq.test()

six_hour = new_ratio_bayesian_p_de %>% 
    mutate(gene = gsub("\\..*", "", gene)) %>%  
    filter(new_rna_sig != "unclear") %>% 
    left_join(annotables::grch38 %>% select(ensgene,symbol), by = c("gene" = "ensgene")) %>% 
    select(time,symbol,total_rna_sig,new_rna_sig) %>% 
    filter(!is.na(symbol)) %>% 
    unique() %>% 
    mutate(axonal = symbol %in% ax) %>% 
    filter(time == 6) %>% 
    mutate(total_new = paste0(total_rna_sig,"_",new_rna_sig)) %>% 
    select(total_new,axonal) %>% 
    table() %>% 
    chisq.test()

corrplot(one_hour$residuals, is.cor = FALSE)
corrplot(two_hour$residuals, is.cor = FALSE)
corrplot(six_hour$residuals, is.cor = FALSE)

corrplot(100*one_hour$residuals^2/one_hour$statistic,is.corr = FALSE)
corrplot(100*two_hour$residuals^2/two_hour$statistic,is.corr = FALSE)
corrplot(100*six_hour$residuals^2/six_hour$statistic,is.corr = FALSE)
```

going to see if RNA with m6a is also downregulated, modeled by above code with axonal fisher
```{r axonal fisher coorelation plot w/ m6a}
m6a <- read_csv("C:/Users/mlomb/Desktop/tracked_files_github/bdnf_4su/data/m6a_sites_hg37.csv")

one_hour_m6a <- new_ratio_bayesian_p_de %>% 
    filter(new_rna_sig != "unclear") %>% 
    mutate(gene = gsub("\\..*", "", gene)) %>%  
    left_join(annotables::grch38 %>% select(ensgene,symbol), by = c("gene" = "ensgene")) %>% 
    select(time,symbol,total_rna_sig,new_rna_sig) %>% 
    filter(!is.na(symbol)) %>% 
    unique() %>% 
    mutate(m6a_site = symbol %in% m6a) %>% 
    filter(time == 1) %>% 
    mutate(total_new = paste(total_rna_sig,new_rna_sig,sep = "_")) %>% 
    select(total_new,m6a_site)%>% 
    table() %>% 
    chisq.test()

two_hour_m6a <- new_ratio_bayesian_p_de %>% 
    filter(new_rna_sig != "unclear") %>% 
    mutate(gene = gsub("\\..*", "", gene)) %>%  
    left_join(annotables::grch38 %>% select(ensgene,symbol), by = c("gene" = "ensgene")) %>% 
    select(time,symbol,total_rna_sig,new_rna_sig) %>% 
    filter(!is.na(symbol)) %>% 
    unique() %>% 
    mutate(m6a_site = symbol %in% m6a) %>% 
    filter(time == 2) %>% 
    mutate(total_new = paste(total_rna_sig,new_rna_sig,sep = "_")) %>% 
    select(total_new,m6a_site)  %>% 
    table() %>% 
    chisq.test()

six_hour_m6a <- new_ratio_bayesian_p_de %>% 
    filter(new_rna_sig != "unclear") %>% 
    mutate(gene = gsub("\\..*", "", gene)) %>%  
    left_join(annotables::grch38 %>% select(ensgene,symbol), by = c("gene" = "ensgene")) %>% 
    select(time,symbol,total_rna_sig,new_rna_sig) %>% 
    filter(!is.na(symbol)) %>% 
    unique() %>% 
    mutate(m6a_site = symbol %in% m6a) %>% 
    filter(time == 6) %>% 
    mutate(total_new = paste(total_rna_sig,new_rna_sig,sep = "_")) %>% 
    select(total_new,m6a_site)  %>% 
    table() %>% 
    chisq.test()

corrplot(one_hour_m6a$residuals, is.cor = FALSE)
corrplot(two_hour_m6a$residuals, is.cor = FALSE)
corrplot(six_hour_m6a$residuals, is.cor = FALSE)

corrplot(100*one_hour_m6a$residuals^2/one_hour_m6a$statistic,is.corr = FALSE)
corrplot(100*two_hour_m6a$residuals^2/two_hour_m6a$statistic,is.corr = FALSE)
corrplot(100*six_hour_m6a$residuals^2/six_hour_m6a$statistic,is.corr = FALSE)
```



YTH binding sites for bdnf vs control from AL 
```{r YTH binding sites}
yth <- as.data.table(janitor::clean_names(fread("C:/Users/mlomb/Desktop/tracked_files_github/bdnf_4su/data/YTH bound mRNAs.csv")))
new_ratio_bayesian_p_de <- read_csv("C:/Users/mlomb/Desktop/tracked_files_github/bdnf_4su/data/new_ratio_bayesian_p_de.csv")

#making a table that collapses the total YTH Binding sites
binding_sum <- yth %>% 
    group_by(target_gene_symbol,target_gene_id) %>% 
    summarize(total_binding = sum(binding_site_records)) %>% 
    ungroup() 

new_ratio_bayesian_p_de %>% 
    mutate(gene = gsub("\\..*", "", gene)) %>%  
    left_join(annotables::grch38 %>% select(ensgene,symbol), by = c("gene" = "ensgene")) %>% 
    # left_join(yth[,.(rbp,target_gene_id,binding_site_records)], by = c("gene" = "target_gene_id")) %>% 
    left_join(binding_sum, by = c("gene" = "target_gene_id")) %>%
    mutate(total_binding = ifelse(is.na(total_binding),0,total_binding)) %>% 
    group_by(time) %>% 
    mutate(yth_binned = ifelse(total_binding ==0 , 'not bound','bound')) %>% 
    ungroup() %>% 
    select(time,gene,mean_bdnf_ntr,mean_control_ntr,yth_binned,total_rna_sig) %>% 
    group_by(time,yth_binned,total_rna_sig) %>% 
    mutate(n_genes = n_distinct(gene)) %>% 
    ungroup() %>% 
    melt(id.vars = c("time","gene","yth_binned", "n_genes","total_rna_sig")) %>% 
    mutate(plot_name = glue::glue("{yth_binned} \n ({n_genes}) genes")) %>% 
    filter(time != 6) %>% 
    ggplot(aes(x = plot_name,
               y = value,fill = variable)) + 
    geom_boxplot() + 
    facet_wrap(total_rna_sig ~ time,scales = 'free') + 
    ylab("New RNA Fraction") + 
    xlab("YTHDF POSTAR3 - Total Binding sites binned (all YTHDF collapsed)") + 
    ggpubr::stat_compare_means(hide.ns = TRUE,
                               label = 'p.signif') + 
    coord_flip()

new_ratio_bayesian_p_de %>% 
    mutate(gene = gsub("\\..*", "", gene)) %>%  
    left_join(annotables::grch38 %>% select(ensgene,symbol), by = c("gene" = "ensgene")) %>% 
    # left_join(yth[,.(rbp,target_gene_id,binding_site_records)], by = c("gene" = "target_gene_id")) %>% 
    left_join(binding_sum, by = c("gene" = "target_gene_id")) %>%
    mutate(total_binding = ifelse(is.na(total_binding),0,total_binding)) %>% 
    group_by(time) %>% 
    mutate(yth_binned = case_when(total_binding < 1 ~ ' no yth',
                                  total_binding <= 10 ~ '10 or fewer',
                                  total_binding <= 100 ~ "100 or fewer",
                                  total_binding <= 1000 ~ "1000 or fewer",
                                  total_binding > 1000 ~ "more than 1000 binding"))  %>% 
    ungroup() %>% 
    select(time,gene,mean_bdnf_ntr,mean_control_ntr,yth_binned,total_rna_sig) %>% 
    group_by(time,yth_binned,total_rna_sig) %>% 
    mutate(n_genes = n_distinct(gene)) %>% 
    ungroup() %>% 
    melt(id.vars = c("time","gene","yth_binned", "n_genes","total_rna_sig")) %>% 
    mutate(plot_name = glue::glue("{yth_binned} \n ({n_genes}) genes")) %>% 
    filter(time != 6) %>% 
    ggplot(aes(x = plot_name,
               y = value,fill = variable)) + 
    geom_boxplot() + 
    facet_wrap(total_rna_sig ~ time,scales = 'free') + 
    ylab("New RNA Fraction") + 
    xlab("YTHDF POSTAR3 - Total Binding sites binned (all YTHDF collapsed)") + 
    ggpubr::stat_compare_means(hide.ns = TRUE,
                               label = 'p.signif') + 
    coord_flip()

```

